---
- name: check if docker daemon file was already setup is installed
  stat: path=/etc/docker/daemon.json
  register: docker_daemon

- name: apt-get update
  apt:
    update_cache: yes

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker’s official GPG key
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    pkg:
    - containerd.io=1.2.10-3
    - docker-ce=5:19.03.4~3-0~ubuntu-xenial
    - docker-ce-cli=5:19.03.4~3-0~ubuntu-xenial


- name: Setup daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json


- name: Setup daemon directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'


- name: Stop docker
  systemd:
    state: stopped
    daemon_reload: yes
    name: docker

- pause:
    seconds: 10

- name: start docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker